from __future__ import annotations

import pytest

from preflight.java_ast import parse_java_source
from preflight.runner import _class_policy


@pytest.mark.business
@pytest.mark.parametrize(
    ("source", "expected"),
    [
        ("package x; public interface X {}", "EXCLUDE_UNSUPPORTED_DECLARATION"),
        ("package x; public @interface X {}", "EXCLUDE_UNSUPPORTED_DECLARATION"),
        ("package x; public enum X { A, B }", "EXCLUDE_STRICT_COHORT"),
        ("package x; public record X(int id, String name) {}", "EXCLUDE_STRICT_COHORT"),
        ("package x; public abstract class X { public abstract void run(); }", "EXCLUDE_ABSTRACT_CLASS"),
        ("package x; // generated by tool\n public class X {}", "EXCLUDE_GENERATED_SOURCE"),
        ("package x; @javax.annotation.Generated(\"tool\") public class X {}", "EXCLUDE_GENERATED_SOURCE"),
        ("package x; class Outer { class X {} }", "EXCLUDE_UNSUPPORTED_DECLARATION"),
    ],
)
def test_excluded_declarations_receive_reason_codes(source, expected):
    java = parse_java_source(source, "src/main/java/x/X.java", expected_name="X")
    status, tags, reasons = _class_policy(java)
    assert status == expected
    assert expected in reasons


@pytest.mark.business
@pytest.mark.parametrize(
    "source",
    [
        "package x; public final class X { public X() {} public int run() { return 1; } }",
        "package x; class X { int run() { return 1; } }",
        "package x; final class X { private X() {} public static int run() { return 1; } }",
    ],
)
def test_final_package_private_and_static_utility_are_not_excluded(source):
    status, tags, reasons = _class_policy(parse_java_source(source, "src/main/java/x/X.java", expected_name="X"))
    assert status is None
    assert reasons == []


@pytest.mark.business
def test_dto_pojo_is_accepted_and_tagged_low_logic():
    source = """package x; public class UserDto {
      private String name;
      public UserDto(String name) { this.name = name; }
      public String getName() { return name; }
      public void setName(String name) { this.name = name; }
    }"""
    java = parse_java_source(source, "src/main/java/x/UserDto.java", expected_name="UserDto")
    status, tags, reasons = _class_policy(java)
    assert status is None
    assert reasons == []
    assert "LOW_LOGIC" in tags


@pytest.mark.business
def test_constructor_only_cut_is_accepted_and_tagged():
    source = """package x; public class ConfigHolder {
      public ConfigHolder(int timeout) {}
    }"""
    java = parse_java_source(source, "src/main/java/x/ConfigHolder.java", expected_name="ConfigHolder")
    status, tags, reasons = _class_policy(java)
    assert status is None
    assert reasons == []
    assert "CONSTRUCTOR_ONLY" in tags
    assert "LOW_LOGIC" in tags


@pytest.mark.business
def test_dao_with_datasource_is_tagged_db_dependent_and_requires_mock():
    source = """package x; import javax.sql.DataSource; public class UserDao {
      private final DataSource ds;
      public UserDao(DataSource ds) { this.ds = ds; }
      public void save() {}
    }"""
    java = parse_java_source(source, "src/main/java/x/UserDao.java", expected_name="UserDao")
    status, tags, reasons = _class_policy(java)
    assert status is None
    assert reasons == []
    assert "DB_DEPENDENT" in tags
    assert "REQUIRES_MOCK" in tags
    assert "DIRECT_CONNECTION" not in tags


@pytest.mark.business
def test_direct_connection_is_a_tag_not_an_automatic_exclusion():
    source = """package x; import java.sql.DriverManager; public class X {
      public void run() throws Exception { DriverManager.getConnection("jdbc:test"); }
    }"""
    status, tags, reasons = _class_policy(parse_java_source(source, "src/main/java/x/X.java", expected_name="X"))
    assert status is None
    assert reasons == []
    assert "DIRECT_CONNECTION" in tags
    assert "DB_DEPENDENT" in tags
    assert "REQUIRES_MOCK" not in tags


@pytest.mark.business
def test_external_http_and_file_io_are_tagged_external_dependent():
    source = """package x; import java.net.http.HttpClient; import java.io.FileInputStream;
    public class Gateway {
      public void fetch() {}
    }"""
    java = parse_java_source(source, "src/main/java/x/Gateway.java", expected_name="Gateway")
    status, tags, reasons = _class_policy(java)
    assert status is None
    assert reasons == []
    assert "EXTERNAL_DEPENDENT" in tags
    assert "REQUIRES_MOCK" in tags


@pytest.mark.business
def test_suspect_test_name_in_production_source_is_not_excluded():
    source = "package x; public class OrderTest { public void execute() {} }"
    java = parse_java_source(source, "src/main/java/x/OrderTest.java", expected_name="OrderTest")
    status, tags, reasons = _class_policy(java)
    assert status is None
    assert reasons == []
    assert "SUSPECT_TEST_NAME" in tags

