from __future__ import annotations

import pytest

from preflight.java_ast import parse_java_source
from preflight.runner import _class_policy


@pytest.mark.business
@pytest.mark.parametrize(
    ("source", "expected"),
    [
        ("package x; public interface X {}", "EXCLUDE_UNSUPPORTED_DECLARATION"),
        ("package x; public enum X { A }", "EXCLUDE_STRICT_COHORT"),
        ("package x; public abstract class X {}", "EXCLUDE_ABSTRACT_CLASS"),
        ("package x; // generated by tool\n public class X {}", "EXCLUDE_GENERATED_SOURCE"),
        ("package x; class Outer { class X {} }", "EXCLUDE_UNSUPPORTED_DECLARATION"),
    ],
)
def test_excluded_declarations_receive_reason_codes(source, expected):
    java = parse_java_source(source, "src/main/java/x/X.java", expected_name="X")
    status, tags, reasons = _class_policy(java)
    assert status == expected
    assert expected in reasons


@pytest.mark.business
@pytest.mark.parametrize(
    "source",
    [
        "package x; public final class X { public X() {} public int run() { return 1; } }",
        "package x; class X { int run() { return 1; } }",
        "package x; final class X { private X() {} public static int run() { return 1; } }",
    ],
)
def test_final_package_private_and_static_utility_are_not_excluded(source):
    status, tags, reasons = _class_policy(parse_java_source(source, "src/main/java/x/X.java", expected_name="X"))
    assert status is None
    assert reasons == []


@pytest.mark.business
def test_direct_connection_is_a_tag_not_an_automatic_exclusion():
    source = """package x; import java.sql.DriverManager; public class X {
      public void run() throws Exception { DriverManager.getConnection(\"jdbc:test\"); }
    }"""
    status, tags, reasons = _class_policy(parse_java_source(source, "src/main/java/x/X.java", expected_name="X"))
    assert status is None
    assert reasons == []
    assert "DIRECT_CONNECTION" in tags
